<?php
/**
 * BTLDECO — Translation helper
 * Reads lang from cookie/session, returns translated strings
 */

function current_lang(): string {
    return $_COOKIE['btl-lang'] ?? $_SESSION['btl-lang'] ?? 'es';
}

function t(string $key): string {
    static $strings = null;
    if ($strings === null) {
        $strings = [
            'es' => [
                // Nav
                'home' => 'Inicio',
                'shop' => 'Tienda',
                'gallery' => 'Galeria',
                'about' => 'Nosotros',
                'contact' => 'Contacto',
                'shop_btn' => 'TIENDA',
                // Breadcrumb
                'breadcrumb_home' => 'Inicio',
                'breadcrumb_shop' => 'Tienda',
                'breadcrumb_checkout' => 'Checkout',
                // Tienda
                'shop_title' => 'Tienda',
                'shop_subtitle' => 'Todos nuestros productos de decoracion',
                'filter_all' => 'Todos',
                'sort_recent' => 'Mas recientes',
                'sort_price_asc' => 'Precio: menor a mayor',
                'sort_price_desc' => 'Precio: mayor a menor',
                'sort_name' => 'Nombre: A-Z',
                'sort_sold' => 'Mas vendidos',
                'add_to_cart' => 'AÑADIR AL CARRITO',
                'sold_out' => 'AGOTADO',
                'no_products' => 'No hay productos disponibles',
                'no_products_cat' => 'No hay productos en esta categoria',
                'view_all' => 'Ver todos los productos',
                'offer' => 'OFERTA',
                'featured' => 'DESTACADO',
                // Producto
                'delivery' => 'Entrega',
                'delivery_time' => '48hs habiles',
                'shipping' => 'Envio',
                'shipping_where' => 'A todo el pais',
                'stock' => 'Stock',
                'available' => 'disponibles',
                'out_of_stock' => 'Agotado — Consultar',
                'product_sold_out' => 'PRODUCTO AGOTADO',
                'check_availability' => 'CONSULTAR DISPONIBILIDAD',
                'ask_whatsapp' => 'CONSULTAR POR WHATSAPP',
                'related' => 'Tambien te puede gustar',
                'inquire' => 'Consultar',
                // Checkout
                'checkout_title' => 'Finalizar compra',
                'checkout_subtitle' => 'Revisa tu pedido, completa tus datos y elegí el metodo de pago',
                'step_order' => 'Tu pedido',
                'step_shipping' => 'Datos de envio',
                'step_payment' => 'Metodo de pago',
                'full_name' => 'Nombre completo',
                'email' => 'Email',
                'phone' => 'Telefono',
                'address' => 'Direccion',
                'number' => 'Numero',
                'floor_apt' => 'Piso / Depto',
                'floor_apt_opt' => '(opcional)',
                'zip_code' => 'Codigo postal',
                'city' => 'Localidad / Barrio',
                'province' => 'Provincia',
                'select_province' => 'Selecciona tu provincia',
                'mercadopago' => 'MercadoPago',
                'mp_desc' => 'Tarjeta de credito, debito o efectivo',
                'transfer' => 'Transferencia bancaria',
                'transfer_desc' => 'CBU / Alias — Confirmacion manual',
                'transfer_data' => 'Datos para transferencia',
                'transfer_note' => 'Envianos el comprobante por WhatsApp para confirmar tu pedido',
                'summary' => 'Resumen',
                'products' => 'Productos',
                'free_shipping' => 'Gratis',
                'discount' => 'Descuento',
                'subtotal' => 'Subtotal',
                'total' => 'Total',
                'confirm_order' => 'CONFIRMAR PEDIDO',
                'secure_payment' => 'Compra 100% segura',
                'safe_payment' => 'Pago seguro',
                'fast_delivery' => 'Entrega en 48hs',
                'free_ship' => 'Envio gratis',
                'back_to_shop' => 'Seguir comprando',
                'coupon_placeholder' => 'Codigo de cupon',
                'coupon_apply' => 'Aplicar',
                'coupon_remove' => 'Quitar',
                'per_unit' => 'c/u',
                // Contact
                'contact_title' => 'Hablemos de<br>tu pedido',
                'contact_desc' => 'Respondemos en menos de 24hs. Tambien podes escribirnos directo por WhatsApp.',
                'send_message' => 'ENVIAR MENSAJE',
                'name_label' => 'NOMBRE',
                'email_label' => 'EMAIL',
                'phone_label' => 'TELEFONO',
                'product_label' => 'PRODUCTO',
                'message_label' => 'MENSAJE',
                'select_product' => 'Selecciona un producto',
                'custom_order' => 'Pedido personalizado',
                'general_inquiry' => 'Consulta general',
                'copyright' => '&copy; 2026 BTLDECO. Todos los derechos reservados.',
                'location' => 'UBICACION',
            ],
            'en' => [
                'home' => 'Home',
                'shop' => 'Shop',
                'gallery' => 'Gallery',
                'about' => 'About',
                'contact' => 'Contact',
                'shop_btn' => 'SHOP',
                'breadcrumb_home' => 'Home',
                'breadcrumb_shop' => 'Shop',
                'breadcrumb_checkout' => 'Checkout',
                'shop_title' => 'Shop',
                'shop_subtitle' => 'All our decoration products',
                'filter_all' => 'All',
                'sort_recent' => 'Most recent',
                'sort_price_asc' => 'Price: low to high',
                'sort_price_desc' => 'Price: high to low',
                'sort_name' => 'Name: A-Z',
                'sort_sold' => 'Best sellers',
                'add_to_cart' => 'ADD TO CART',
                'sold_out' => 'SOLD OUT',
                'no_products' => 'No products available',
                'no_products_cat' => 'No products in this category',
                'view_all' => 'View all products',
                'offer' => 'SALE',
                'featured' => 'FEATURED',
                'delivery' => 'Delivery',
                'delivery_time' => '48 business hours',
                'shipping' => 'Shipping',
                'shipping_where' => 'Nationwide',
                'stock' => 'Stock',
                'available' => 'available',
                'out_of_stock' => 'Sold out — Inquire',
                'product_sold_out' => 'PRODUCT SOLD OUT',
                'check_availability' => 'CHECK AVAILABILITY',
                'ask_whatsapp' => 'ASK VIA WHATSAPP',
                'related' => 'You might also like',
                'inquire' => 'Inquire',
                'checkout_title' => 'Checkout',
                'checkout_subtitle' => 'Review your order, fill in your details and choose payment method',
                'step_order' => 'Your order',
                'step_shipping' => 'Shipping details',
                'step_payment' => 'Payment method',
                'full_name' => 'Full name',
                'email' => 'Email',
                'phone' => 'Phone',
                'address' => 'Address',
                'number' => 'Number',
                'floor_apt' => 'Floor / Apt',
                'floor_apt_opt' => '(optional)',
                'zip_code' => 'Zip code',
                'city' => 'City / Neighborhood',
                'province' => 'Province',
                'select_province' => 'Select your province',
                'mercadopago' => 'MercadoPago',
                'mp_desc' => 'Credit card, debit card or cash',
                'transfer' => 'Bank transfer',
                'transfer_desc' => 'CBU / Alias — Manual confirmation',
                'transfer_data' => 'Transfer details',
                'transfer_note' => 'Send us the receipt via WhatsApp to confirm your order',
                'summary' => 'Summary',
                'products' => 'Products',
                'free_shipping' => 'Free',
                'discount' => 'Discount',
                'subtotal' => 'Subtotal',
                'total' => 'Total',
                'confirm_order' => 'CONFIRM ORDER',
                'secure_payment' => '100% secure purchase',
                'safe_payment' => 'Secure payment',
                'fast_delivery' => 'Delivery in 48h',
                'free_ship' => 'Free shipping',
                'back_to_shop' => 'Continue shopping',
                'coupon_placeholder' => 'Coupon code',
                'coupon_apply' => 'Apply',
                'coupon_remove' => 'Remove',
                'per_unit' => 'each',
                'contact_title' => 'Let\'s talk about<br>your order',
                'contact_desc' => 'We respond within 24 hours. You can also message us directly on WhatsApp.',
                'send_message' => 'SEND MESSAGE',
                'name_label' => 'NAME',
                'email_label' => 'EMAIL',
                'phone_label' => 'PHONE',
                'product_label' => 'PRODUCT',
                'message_label' => 'MESSAGE',
                'select_product' => 'Select a product',
                'custom_order' => 'Custom order',
                'general_inquiry' => 'General inquiry',
                'copyright' => '&copy; 2026 BTLDECO. All rights reserved.',
                'location' => 'LOCATION',
            ],
        ];
    }
    $lang = current_lang();
    return $strings[$lang][$key] ?? $strings['es'][$key] ?? $key;
}
